{% set name = "daqp" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/daqp-{{ version }}.tar.gz
  sha256: 2e81a0bfa2f6e36e53c6fcc55d962c5b7f61d93a97909f6350c1fe26ce37af58

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - wheel
    - cython
    - pip
  run:
    - python
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.12") }}  # [osx and x86_64]

test:
  imports:
    - daqp
  commands:
    - pip check
  requires:
    - pip
    - numpy

about:
  home: http://github.com/darnstrom/daqp
  summary: 'DAQP: A dual active-set QP solver'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - darnstrom
