{% set name = "daqp" %}
{% set version = "0.5.1.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/daqp-{{ version }}.tar.gz
  sha256: f314f7405fca36d74ac0ed0f2b289d9aa9f8c56768f3103bdc3459fde8b61f6c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - wheel
    - cython <3
    - pip
  run:
    - python
    - numpy
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.12") }}  # [osx and x86_64]

test:
  imports:
    - daqp
  commands:
    - pip check
  requires:
    - pip
    - numpy

about:
  home: http://github.com/darnstrom/daqp
  summary: 'DAQP: A dual active-set QP solver'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - darnstrom
