{% set name = "daqp" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/daqp-{{ version }}.tar.gz
  sha256: baf8b25fe7cbdbb09da0783cb47479d2dcb2bc927ceffc15836766529d3c962f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - pip                                    # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - cython <3
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - daqp
  commands:
    - pip check
  requires:
    - pip
    - numpy

about:
  home: http://github.com/darnstrom/daqp
  summary: 'DAQP: A dual active-set QP solver'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - darnstrom
