schema_version: 1

context:
  version: "0.8.1"

package:
  name: daqp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/daqp/daqp-${{ version }}.tar.gz
  sha256: 918bbfbd0efe8ccca8218f0593355e999e8131eea887e573bc704e3a2f33c2f0

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - cython
    - setuptools
    - pip
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - daqp
  - requirements:
      run:
        - pip
        - python
    script:
      - pip check

about:
  summary: "DAQP: A dual active-set QP solver"
  license: MIT
  license_file: LICENSE
  homepage: http://github.com/darnstrom/daqp

extra:
  recipe-maintainers:
    - darnstrom
    - flferretti
