schema_version: 1

context:
  version: "0.8.7"

package:
  name: daqp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/daqp/daqp-${{ version }}.tar.gz
  sha256: 62cfd3208a9841ffb6a87d145bce930a0e87ecea802a5ffed5d0146c4b133a54

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - cython
    - setuptools
    - pip
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - daqp
  - requirements:
      run:
        - pip
        - python
    script:
      - pip check

about:
  summary: "DAQP: A dual active-set QP solver"
  license: MIT
  license_file: LICENSE
  homepage: http://github.com/darnstrom/daqp

extra:
  recipe-maintainers:
    - darnstrom
    - flferretti
